#!/bin/sh

set -e
set -u

cd "$OPENSHIFT_REPO_DIR"

pythondir="$OPENSHIFT_DEPENDENCIES_DIR/python"

if [ ! -d "$pythondir" ]
then
    virtualenv "$pythondir"
fi

"$pythondir/bin/pip" -r requirements_backend.txt

. "$OPENSHIFT_REDLAND_DIR/bin/activate-redland"

cd backend
"$pythondir/bin/python" setup.py install
