#!/bin/bash

set -e
set -u

source "$OPENSHIFT_CARTRIDGE_SDK_BASH"

# Create a user for the catalog if not already existing
if ! psql -A -t -c "select * from pg_user where usename = 'catalog'" | grep -q '^catalog|'
then
    client_message "Creating database user: catalog"

    # Just reuse the admin password instead of having to track another one
    psql -c "CREATE ROLE catalog NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$OPENSHIFT_POSTGRESQL_DB_PASSWORD';"
fi

# Create databases for the works and public stores
if ! psql -A -t -c "select * from pg_database where datname = 'catalog_works'" | grep -q '^catalog_works|'
then
    client_message "Creating database: catalog_works"

    psql -c "CREATE DATABASE catalog_works OWNER catalog ENCODING 'UTF-8';"
fi

if ! psql -A -t -c "select * from pg_database where datname = 'catalog_public'" | grep -q '^catalog_public|'
then
    client_message "Creating database: catalog_public"

    psql -c "CREATE DATABASE catalog_public OWNER catalog ENCODING 'UTF-8';"
fi

# Initiliase the stores
source "$OPENSHIFT_REPO_DIR/.openshift/store_config"
"$OPENSHIFT_REPO_DIR/backend/create_store.py"

