import os

BROKER_URL = os.getenv('CATALOG_BROKER_URL', 'amqp://guest@localhost:5672//')
CELERY_TASK_SERIALIZER='json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER='json'
CELERY_RESULT_BACKEND = 'amqp'
CELERY_TASK_RESULT_EXPIRES = 30
CELERY_TASK_RESULT_DURABLE = False
