// Do not edit this file to change the catalog configuration!
// Instead edit development/test/production.js or set env vars.
// For more info, see doc/config.md

module.exports = {
    catalog: {
        autoIndex: false,

        // Base URL for MongoDB connections, unless the
        // module-specific settings specify a full URL.
        mongodbURL: 'mongodb://localhost/',

        //
        // Module-specific configuration
        //

        frontend: {
            baseURL: 'http://localhost:8004',
            port: '8004',

            // Either a plain name, or a full mongodb: URL
            sessionDB: 'frontend-session',

            secret: 'rainbow pegasi',

            static: '/public',
            static_lib: '/../public',
        },

        auth: {
            db: 'auth',
        },
    },
};
